In [2]:
import numpy as np
from pprint import pprint

In [3]:
import sympy as sp
import numpy.linalg

sp.var('t')
m = 5  # m must be non-symbolic for sympy to get eigs...

A = np.vstack((np.hstack((np.zeros((2, 2)), np.eye(2))), np.zeros((2, 4))))
B = np.vstack((np.zeros((2, 2)), np.eye(2)/m))
print("A = ")
pprint(A)
print("eigs of A = ")
pprint(np.linalg.eig(A)[0])
# pprint(np.linalg.inv(A))

A = 
array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])
eigs of A = 
array([0., 0., 0., 0.])


In [4]:
AB = np.vstack((np.hstack((A, B)), np.zeros((2, 6))))
pprint(AB)
print(np.shape(AB))
print("eigs of AB = ")
pprint(np.linalg.eig(AB)[0])

array([[0. , 0. , 1. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 1. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0.2, 0. ],
       [0. , 0. , 0. , 0. , 0. , 0.2],
       [0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. ]])
(6, 6)
eigs of AB = 
array([0., 0., 0., 0., 0., 0.])


In [5]:
# redo with m as symbolic
%reset
import numpy as np
from pprint import pprint
import sympy as sp
import numpy.linalg

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


*Use eigenvalues to solve for e^At...*

In [9]:
sp.var('m, t')

A = np.vstack((np.hstack((np.zeros((2, 2)), np.eye(2))), np.zeros((2, 4))))
B = np.vstack((np.zeros((2, 2)), np.eye(2)/m))
AB = np.vstack((np.hstack((A, B)), np.zeros((2, 6))))
M = AB@AB*(1 + t**2)/2 + AB*t + np.eye(np.shape(AB)[0])
pprint(M)

array([[1.00000000000000, 0, 1.0*t, 0, 0.5*(t**2 + 1)/m, 0],
       [0, 1.00000000000000, 0, 1.0*t, 0, 0.5*(t**2 + 1)/m],
       [0, 0, 1.00000000000000, 0, 1.0*t/m, 0],
       [0, 0, 0, 1.00000000000000, 0, 1.0*t/m],
       [0, 0, 0, 0, 1.00000000000000, 0],
       [0, 0, 0, 0, 0, 1.00000000000000]], dtype=object)


In [10]:
Ad = M[0:4, 0:4]
pprint(Ad)

array([[1.00000000000000, 0, 1.0*t, 0],
       [0, 1.00000000000000, 0, 1.0*t],
       [0, 0, 1.00000000000000, 0],
       [0, 0, 0, 1.00000000000000]], dtype=object)


In [11]:
Bd = M[0:4, 4:6]
pprint(Bd)

array([[0.5*(t**2 + 1)/m, 0],
       [0, 0.5*(t**2 + 1)/m],
       [1.0*t/m, 0],
       [0, 1.0*t/m]], dtype=object)


In [12]:
sp.var('x, z, dx, dz, fx, fz, g')
X = np.array([x, z, dx, dz]).T
U = np.array([fx, fz]).T
G = np.array([0, 0, 0, -g]).T
xk1 = Ad@X + Bd@U + G
pprint(xk1)

array([1.0*dx*t + 0.5*fx*(t**2 + 1)/m + 1.0*x,
       1.0*dz*t + 0.5*fz*(t**2 + 1)/m + 1.0*z, 1.0*dx + 1.0*fx*t/m,
       1.0*dz + 1.0*fz*t/m - g], dtype=object)
